### ISSUE TITLE
[FEATURE] Keep default inventory, but add new items

### ISSUE THREAD

**Issue by Oyplap** [MrAfitol/InventoryControl#3]
Sorry if i'm requesting to many features, but is it perhaps possible if you could add a config option to keep the default inventory, but being able to add extra items?

For example:

```
inventory:
  Scientist:
    keepItems: true
    Coin: 100
```
    
 
 Inventory would look like this:
![Screenshot 2023-01-06 115909](https://user-images.githubusercontent.com/45702131/210999571-de256fdb-1603-408e-9b5c-e2a6b8fff03f.png)
